import { calc_scene_idx_fn } from "../consts.js"

const SCENE_DESCRIPTION_LIST = [
  'Scenario 1.1: M&A for A Pharmaceutical Company<br> Introduction <br> AAA is a pharmaceutical company that aims to expand its business, and it would like to acquire a new business sector. The information about the candidates is collected by your subordinates, and now you are making the final decision with the top decision group. Your group should select the best target which can benefit AAA the most, and the target will generate the highest outcome for AAA.  <br> <br>  Criteria <br>  In the game, you will get multiple cards in each round. <br> These cards are about the four potential targets: ME Co., NJ Co., PI Co., and SA Co. You and your group members are exchanging the information for each member had to form the group decision. Please present relevant information cards to help your group make a better decision. ',
  'Scenario-1.2: M&A for A E-commerce Company<br> Introduction <br> AAA is an e-commerce company that aims to expand its business. It does not limit itself to the service of e-commerce. AAA would also like to involve in trending business to enhance its future growth and revenue. The board is currently interested in three different services: online on-demand video streaming, fresh food e-commerce, and cloud computing services. The information about the candidates is collected by your subordinates, and now you are making the final decision with the top decision group. <br>  Your group should select the best target which can benefit AAA the most, and the target will <b>generate the highest outcome</b> for AAA.<br> <br>  Criteria <br>  In the game, you will get multiple cards in each round. These cards are about the four potential targets: X Co., Y Co., Z Co., and SA Co. You and your group members exchange the information for each member to form the group decision. Please present relevant information cards to help your group make a better decision. ',
  'Scenario-1.3: Who holds the next game?<br> Introduction<br> You are a member of the Athletic Games Committee, and your organization is trying to make a decision for the host city of the next game. Based on the information you own or are informed of, you will select the best target which will generate the highest outcome and follow the basic requirements. The factors presented in the group will include : <br> (1) funds and sponsors,<br>  (2) transportation, <br> (3) game fields,<br>  (4) residents\' attitude to the game, <br> (5) experience in holding large campaigns, etc. <br> <br>  Criteria <br>  There are four cities that apply to become the host: Auro, Basa, Cilia, and Debu. Please follow the instruction and the information shared in your group to pick up the best host for the next game.',
  'Scenario-2.1: A Detective Game - The beloved collections <br> Introduction 1 <br> 	There is a crime that happened in the neighborhood last night. The victims beloved collections were stolen. You are in the investigation team to help identify the possible suspect who committed the crime. In the game, you will play as one of the characters (the victim, the neighbor, or the detective). You have a common interest: you want to identify the criminal from the three suspects correctly. You will share the information you got with your group and suggest who is the possible crime in each round. <br> Please present relevant information cards to your group. No prior assumption needs to be made. <br> <br> Characters <br> All players will receive information provided from different characters below. <br> •          The Victim <br> 	Your favorite music records collections were stolen last night. To help identify the suspect, please provide relative information about the appearances, the place you stored them, or any other characteristics for the collections. <br> • A Neighbor <br>   You are a kind neighbor who would like to help your friend. Their favorite music records collections were stolen. Your neighbor promise you to reward you if the correct guy is identified. Tell us what you see, what you know, or some any relative information that can help. Please provide the information that might be relevant to help identify the suspect. <br> • A Detective <br>  You are hired to identify the suspect in a case for stolen collections. You had already gathered some information about the possible suspects. However, some important clues are still missing. You would like to talk with the victim and potential witnessers to find out more information. Provide some clues to guide or remind them to come up with important information. ',
  'Scenario-2.2: A Detective Game - Identify the murder 1 <br> Instruction <br>  There is a crime that happened in the village last night. The victim is a famous hotel owner. You are in the investigation team to help identify the possible suspect who committed the crime. In the game, you will get information from multiple different characters (the prophet, the detective, or the villager). Some of the statements are unrelated or even wrong. You want to identify the criminal from the four suspects correctly with the correct information. <br>  You will share the important information you got with your group and suggest who is the possible crime in each round. Please present relevant information cards to your group. No prior assumption needs to be made. <br> <br>  Characters <br>  All players will receive information from various characters in this game. Depending on the characters, there are different types of information cards. Three types of characters are included: <br>  •          The Prophet <br>              A prophet is a person who can see into the past scene and foresee the future. However, their ability has limitations. Only about 1/3 of the vision or prophecy is correct. (The information card they get might be one mistake among the three, and the prophet does not know which is wrong either.)  <br>  •          The Detective <br>              A person who makes a judgment on legal cases. They also collect and provide evidence to support their deduction. <br>  •          A Villager <br>              A person with no unique ability or just wants to provide information about what they have seen. <br>  •          A Former Employee <br>              A person who knows about the relationship between the suspects and the victim, and he/she is familiar with the hotel daily operation. <br>  Suspects <br>  There are four suspects in this scenario: <br>  1.        Owner’s brother <br>  2.        Owner’s wife <br>  3.        The counter <br>  4.        The chef <br> ',
  'Scenario-2.3: A Detective Game - Identify the murder 2 <br> Instruction <br>  There is a crime that happened in the West Realm last night. The victim is the lord of the West Realm. You are in the investigation team to help identify the possible suspect who committed the crime. You have a common interest: you want to identify the criminal from the four suspects correctly (or it is possible that the lord of the West Realm committed suicide).  <br>  You will share the information you got with your group and suggest who is the possible crime in each round. Please present relevant information cards to your group. No prior assumption needs to be made. <br> <br> Suspects <br> 1.        The lord committed suicide <br> 2.        The servant <br> 3.        The son of the lord <br> 4.        The commander  <br> 5.        The ambassador from the East Realm <br>',
  'Scenario-3.1: Fact Tests - A Chronic Disease, Disease X <br> Introduction <br>  In this scenario, you and your teammates are discussing a Chronic Disease, Disease X. You will learn about the findings, causes, symptoms, etc. for the disease. You will be asked several questions after some cards are presented. At the end of the game, your group will be asked a final question based on the information in the game. <br> <br>  Instruction <br>  In the game, you will get multiple information cards for each round. You can see your teammates learning about the topic during the game. After the information exchange with your group, several questions will be asked to the players. You should make some judgments and choose the best answer to the questions. There could be one or multiple answers to a question, while the number of answers you should select will be suggested. <br>  These information cards might be relevant, irrelevant, or misleading to the discussed topic. Please present relevant information to help your teammates make correct judgments during the game. <br> ',
  'Scenario 3.2: Fact Tests - Food and Cancer <br> Introduction <br> In this scenario, you and your teammates are discussing some food and related cancer. You will learn about the chemicals in food and the reasons that lead to cancer. You will be asked several questions after some cards are presented. At the end of the game, your group will be asked a final question based on the information in the game. <br> <br>  Instruction  <br> In the game, you will get multiple information cards for each round. You can see your teammates learning about the topic during the game. After the information exchange with your group, several questions will be asked to the players. You should make some judgments and choose the best answer to the questions. There could be one or multiple answers to a question, while the number of answers you should select will be suggested. <br> <br>  These information cards might be relevant, irrelevant, or misleading to the discussed topic. Please present relevant information to help your teammates make correct judgments during the game. <br>',
  'Scenario 3.3: Fact Tests - What leads to sea level rise? <br> Introduction  <br> In this scenario, you and your teammates are discussing what leads to rising sea levels. You will learn about the facts, causes, impacts, etc., of sea level rise. You will be asked several questions after some cards are presented. At the end of the game, your group will be asked a final question based on the information in the game. <br> <br> Instruction <br> In the game, you will get multiple information cards for each round. You can see your teammates learning about the topic during the game. After the information exchange with your group, several questions will be asked to the players. You should make some judgments and choose the best answer to the questions. There could be one or multiple answers to a question, while the number of answers you should select will be suggested. <br> <br> These information cards might be relevant, irrelevant, or misleading to the discussed topic. Please present relevant information to help your teammates make correct judgments during the game. <br>'
]

/**
 * 
 * @param {number} scene_id 
 * @param {number} scene_type_id 
 * @return {string} Scene Description
 */
export function get_scene_description(scene_id, scene_type_id) {
  return SCENE_DESCRIPTION_LIST[calc_scene_idx_fn(scene_id, scene_type_id)]
}